import Head from "next/head";
import Link from "next/link";
import Script from "next/script";
import Footer from "../../comps/Footer";
import SendMessage from "../../comps/SendMessage";
import { Header } from "../skills";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Victor Ibironke | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://kit.fontawesome.com/2024398ef7.js"
          crossorigin="anonymous"
        ></script>
        <script src="https://smtpjs.com/v3/smtp.js"></script>
      </Head>
      <Header />
      <SendMessage location="contact" />
      <div className="socials">
        <Social
          src="/instagram.svg"
          to="https://www.instagram.com/victor.ibironke_"
          alt="instagram"
        />
        <Social
          src="/twitter.svg"
          to="https://www.twitter.com/victoribironke_"
          alt="twitter"
        />
        <Social
          src="/facebook.svg"
          to="https://www.facebook.com/victor.ibironke.963"
          alt="facebook"
        />
        <Social
          src="/linkedin.svg"
          to="https://www.linkedin.com/in/victor-ibironke"
          alt="linkedin"
        />
        <Social
          src="/github.svg"
          to="https://www.github.com/victoribironke"
          alt="github"
        />
        <Social
          src="/tiktok.svg"
          to="https://www.tiktok.com/@vdiqbd"
          alt="tiktok"
        />
      </div>
      <Footer />
    </>
  );
};

const Social = (props) => {
  return (
    <Link target="_blank" className="social" href={props.to}>
      <img src={props.src} alt={props.alt} />
    </Link>
  );
};

export default Contact;
