import Head from "next/head";
import Script from "next/script";
import Footer from "../../comps/Footer";
import Project from "../../comps/Project";
import { Header } from "../skills";

const Projects = () => {
  return (
    <>
      <Head>
        <title>Victor Ibironke | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://kit.fontawesome.com/2024398ef7.js"
          crossorigin="anonymous"
        ></script>
        <script src="https://smtpjs.com/v3/smtp.js"></script>
      </Head>
      <Header />
      <Project />
      <Footer />
    </>
  );
};

export default Projects;
