import Head from "next/head";
import Script from "next/script";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Proj } from "../../comps/Projects";

const Projects = () => {
  const [projectsObject, setProjectsObject] = useState([]);
  useEffect(() => {
    document.querySelector("body").classList.remove("load");
    fetch("/projects.json")
      .then((res) => res.json())
      .then((data) => {
        setProjectsObject(data);
      })
      .catch((err) => console.error(err));
    setTimeout(() => document.querySelector("body").classList.add("load"), 200);
  });

  return (
    <>
      <Head>
        <title>Victor Ibironke | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <Script
          src="https://kit.fontawesome.com/2024398ef7.js"
          crossorigin="anonymous"
        />
      </Head>
      <Link href={"/"} className="back">
        <img src="/arrow-left.svg" alt="go back" />
        <p>Back</p>
      </Link>
      <div className="wrapper">
        {projectsObject.map((proj) => (
          <Proj
            name={proj.name}
            code={proj.code}
            site={proj.site}
            stack={proj.stack}
            key={proj.id}
          />
        ))}
      </div>
    </>
  );
};

export default Projects;
