import Head from "next/head";
import Script from "next/script";
import Skills from "../../comps/Skills";
import Footer from "../../comps/Footer";
import Link from "next/link";

const SkillsHome = () => {
  return (
    <>
      <Head>
        <title>Victor Ibironke | Skills</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <script
          src="https://kit.fontawesome.com/2024398ef7.js"
          crossorigin="anonymous"
        ></script>
        <script src="https://smtpjs.com/v3/smtp.js"></script>
      </Head>
      <Header />
      <Skills />
      <Footer />
    </>
  );
};

const Header = () => {
  return (
    <div className="header">
      <Link className="link" href="/">
        <img src="/arrow-left.svg" alt="arrow" />
        Back
      </Link>
    </div>
  );
};

export default SkillsHome;
export { Header };
