import Head from "next/head";
import About from "../comps/About";
import Header from "../comps/Header";
import SendMessage from "../comps/SendMessage";
import Footer from "../comps/Footer";
import Script from "next/script";
import Techs from "../comps/Techs";
import Project from "../comps/Project";
import Socials from "../comps/Socials";

const Home = () => {
  return (
    <>
      <Head>
        <title>Victor Ibironke</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <Script
          src="https://kit.fontawesome.com/2024398ef7.js"
          crossorigin="anonymous"
        />
        <script src="https://smtpjs.com/v3/smtp.js"></script>
      </Head>
      <div
        className="
    left"
      >
        <Header />
        <About />
      </div>
      <div className="right">
        <p className="projects">Projects</p>
        <Project />
        <p className="projects">Technologies</p>
        <Techs />
        <SendMessage />
        <Socials />
        <Footer />
        <div id="hide">
          <a href="https://icons8.com/icon/8443/coffee-to-go">Coffee to Go</a>
          <a href="https://icons8.com">Icons8</a>
          <a href="https://icons8.com/icon/kg46nzoJrmTR/express-js">
            Express Js
          </a>
          <a href="https://icons8.com">Icons8</a>
          <a target="_blank" href="https://icons8.com/icon/39372/cv">
            CV
          </a>
          <a target="_blank" href="https://icons8.com">
            Icons8
          </a>
        </div>
      </div>
    </>
  );
};

export default Home;
