import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "blog",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <main className="max-w-3xl w-full flex flex-col gap-6">{children}</main>
  );
};

export default RootLayout;
