import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "blog",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="antialiased dark flex items-center justify-center flex-col px-6 py-12">
        <main className="max-w-3xl w-full flex flex-col gap-6">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
